#include "album_cover.h"
#include "polygondwanaland_128.h"
#include <gba_dma.h>
#include <gba_systemcalls.h>

// Album cover display state
static bool is_initialized = 0;

void init_album_cover(void) {
    if (is_initialized) return;
    
    // Set up BG0 for album cover (regular tiled background) 
    // Use different screen base to avoid conflict with BG2 (main background)
    // BG1 uses SCREEN_BASE(30), BG2 uses SCREEN_BASE(29), so use SCREEN_BASE(28)
    REG_BG0CNT = SCREEN_BASE(28) | CHAR_BASE(2) | BG_PRIORITY(1) | BG_256_COLOR | BG_SIZE_0;
    
    // Center the 128x128 artwork on the 240x160 screen
    // Album is on left side, needs to move right by half its width
    // Half width of 128x128 image = 64 pixels
    REG_BG0HOFS = -64;  // Negative scroll moves image right on screen
    REG_BG0VOFS = -2;   // Move down 2 pixels for breathing room at top
    
    // Load the properly converted Polygondwanaland artwork
    // 1. Load palette with RGB channel fix
    while (REG_DMA3CNT & DMA_ENABLE) VBlankIntrWait();
    
    // Load the complete original album palette first
    for (int i = 0; i < 256; i++) {
        u16 originalColor = polygondwanaland_128Pal[i];
        u16 r = (originalColor & 0x1F);           // Extract R
        u16 g = (originalColor >> 5) & 0x1F;     // Extract G  
        u16 b = (originalColor >> 10) & 0x1F;    // Extract B
        
        // Swap R and B channels to fix the color mapping
        BG_PALETTE[i] = b | (g << 5) | (r << 10);  // B, G, R instead of R, G, B
    }
    
    // Dynamic background and text colors based on current track
    // Import track detection function
    extern int is_final_track_8ad(void);
    
    if (is_final_track_8ad()) {
        // "The Fourth Color" - white background, black text
        BG_PALETTE[0] = RGB5(31, 31, 31);  // White background
        BG_PALETTE[16] = RGB5(0, 0, 0);    // Color 0 of palette 1: transparent/black  
        BG_PALETTE[17] = RGB5(0, 0, 0);    // Color 1 of palette 1: black text
    } else {
        // All other tracks - Game Boy colors
        BG_PALETTE[0] = RGB5(19, 23, 1);   // Game Boy bright green background
        BG_PALETTE[16] = RGB5(0, 0, 0);    // Color 0 of palette 1: transparent/black
        BG_PALETTE[17] = RGB5(1, 7, 1);    // Color 1 of palette 1: darkest Game Boy green text
    }
    
    // 2. Load tile data to character base 2 FIRST
    while (REG_DMA3CNT & DMA_ENABLE) VBlankIntrWait();
    dmaCopy(polygondwanaland_128Tiles, PATRAM8(2, 0), polygondwanaland_128TilesLen);
    
    // No pixel manipulation needed - grit should handle palette reservation
    
    // 3. Set up screen entries at our allocated screen base
    u16* screenEntries = SCREEN_BASE_BLOCK(28);
    
    // Clear screen first
    for (int i = 0; i < 32 * 32; i++) {
        screenEntries[i] = 0;
    }
    
    // Load the actual 128x128 album cover using the proper tilemap
    // Simply copy the entire 32x32 tilemap as generated by grit
    for (int i = 0; i < 1024; i++) {
        screenEntries[i] = polygondwanaland_128Map[i];
    }
    
    is_initialized = 1;
}

void cleanup_album_cover(void) {
    if (!is_initialized) return;
    
    // Completely disable BG0 by clearing its enable bit in the main mode
    // and reset scrolling offsets
    REG_BG0HOFS = 0;
    REG_BG0VOFS = 0;
    
    // Clear the tilemap to remove any displayed tiles
    u16* screenEntries = SCREEN_BASE_BLOCK(28);
    for (int i = 0; i < 32 * 32; i++) {
        screenEntries[i] = 0;
    }
    
    // Set BG0 to lowest priority as backup
    REG_BG0CNT = SCREEN_BASE(28) | CHAR_BASE(2) | BG_PRIORITY(3) | BG_256_COLOR | BG_SIZE_0;
    
    is_initialized = 0;
}

void update_album_cover_colors(void) {
    // Import track detection function
    extern int is_final_track_8ad(void);
    
    if (is_final_track_8ad()) {
        // "The Fourth Color" - white background, black text
        BG_PALETTE[0] = RGB5(31, 31, 31);  // White background
        BG_PALETTE[16] = RGB5(0, 0, 0);    // Color 0 of palette 1: transparent/black  
        BG_PALETTE[17] = RGB5(0, 0, 0);    // Color 1 of palette 1: black text
    } else {
        // All other tracks - Game Boy colors
        BG_PALETTE[0] = RGB5(19, 23, 1);   // Game Boy bright green background
        BG_PALETTE[16] = RGB5(0, 0, 0);    // Color 0 of palette 1: transparent/black
        BG_PALETTE[17] = RGB5(1, 7, 1);    // Color 1 of palette 1: darkest Game Boy green text
    }
}

// No update or render functions needed - the background displays automatically once initialized